// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZGK9hIQHqWTGpfV1vwT1YDcSxLapEDiA',
    appId: '1:923773276812:web:d566f244ad95e8b95b21a9',
    messagingSenderId: '923773276812',
    projectId: 'fir-project-ee12a',
    authDomain: 'fir-project-ee12a.firebaseapp.com',
    storageBucket: 'fir-project-ee12a.firebasestorage.app',
    measurementId: 'G-8FCM3G5FF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWDTt_6e1RgwbWlTCsjpPd06cCoO5Mf4',
    appId: '1:923773276812:android:1e4482c0de37a56d5b21a9',
    messagingSenderId: '923773276812',
    projectId: 'fir-project-ee12a',
    storageBucket: 'fir-project-ee12a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrDjzw73IyBIE5HJp9KMpVvjWzDONW0_c',
    appId: '1:923773276812:ios:6c687731de0511775b21a9',
    messagingSenderId: '923773276812',
    projectId: 'fir-project-ee12a',
    storageBucket: 'fir-project-ee12a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDjzw73IyBIE5HJp9KMpVvjWzDONW0_c',
    appId: '1:923773276812:ios:6c687731de0511775b21a9',
    messagingSenderId: '923773276812',
    projectId: 'fir-project-ee12a',
    storageBucket: 'fir-project-ee12a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZGK9hIQHqWTGpfV1vwT1YDcSxLapEDiA',
    appId: '1:923773276812:web:5a7e4b95abcfdaa75b21a9',
    messagingSenderId: '923773276812',
    projectId: 'fir-project-ee12a',
    authDomain: 'fir-project-ee12a.firebaseapp.com',
    storageBucket: 'fir-project-ee12a.firebasestorage.app',
    measurementId: 'G-C6VYWMGF49',
  );
}
